;(function(){ var g = (typeof window!=='undefined')?window:globalThis;
g.DR_DATA = {
  words: [
    "cat","dog","house","tree","sun","moon","star","cloud","rain","snowman",
    "pizza","rocket","car","boat","fish","apple","banana","robot","crown","key",
    "balloon","guitar","umbrella","ladder","clock","cactus","ghost","dragon","castle","rainbow",
    "lion","tiger","bear","monkey","elephant","giraffe","zebra","horse","cow","pig",
    "sheep","goat","duck","chicken","owl","penguin","rabbit","mouse","frog","snake",
    "turtle","snail","bee","butterfly","ladybug","spider","ant","crab","octopus","whale",
    "dolphin","shark","seahorse","starfish","jellyfish","hedgehog","fox","wolf","deer","squirrel",
    "kangaroo","koala","panda","camel","donkey","bat","dinosaur","unicorn","dove","parrot",
    "burger","hotdog","donut","cupcake","cookie","cake","icecream","lollipop","candy","popcorn",
    "sandwich","taco","pancake","egg","cheese","bread","carrot","corn","tomato","potato",
    "pumpkin","strawberry","cherry","grape","lemon","orange","pear","peach","watermelon","pineapple",
    "coconut","mushroom","broccoli","pepper","onion","milk","coffee","teapot","cup","bottle",
    "spoon","fork","knife","plate","bowl","pot","pan","kettle","jar","basket",
    "flower","leaf","grass","bush","palm","mountain","volcano","island","river","lake",
    "wave","fire","lightning","tornado","snowflake","icicle","rock","shell","feather","acorn",
    "vine","seed","log","stump","pond","waterfall","desert","forest","hill","cave",
    "chair","table","bed","lamp","door","window","mirror","clockface","couch","bookshelf",
    "book","pencil","pen","crayon","brush","scissors","ruler","glue","stapler","eraser",
    "backpack","hat","cap","shoe","boot","sock","glove","scarf","shirt","pants",
    "dress","skirt","tie","belt","button","zipper","ring","necklace","watch","glasses",
    "phone","camera","television","radio","laptop","keyboard","remote","battery","bulb","plug",
    "magnet","flashlight","candle","match","lantern","hammer","wrench","screwdriver","nail","saw",
    "axe","shovel","rake","broom","bucket","hose","wheelbarrow","toolbox","gear","spring",
    "wagon","truck","bus","train","plane","raft","ship","jet","bike","scooter",
    "motorcycle","tractor","helicopter","submarine","sailboat","canoe","van","taxi","ambulance","firetruck",
    "anchor","wheel","tire","engine","propeller","glider","parachute","surfboard","sled","skateboard",
    "wizard","fairy","mermaid","knight","pirate","ninja","clown","dwarf","alien","monster",
    "witch","vampire","skeleton","zombie","genie","troll","giant","gnome","angel","superhero",
    "sword","shield","wand","potion","scroll","treasure","gem","gold","map","compass",
    "drum","trumpet","piano","violin","flute","harp","bell","whistle","microphone","banjo",
    "ball","dice","chess","puzzle","kite","yoyo","top","marble","teddy","blocks",
    "heart","diamond","circle","square","triangle","arrow","envelope","stamp","gift","ribbon",
    "flag","tent","bridge","tower","lighthouse","windmill","fountain","fence","gate","mailbox",
    "clockwork","gingerbread","scarecrow","totem","igloo","teepee","pyramid","statue","throne","cauldron"
  ],
  easy: [
    "cat","dog","house","tree","sun","moon","star","cloud","rain","snowman",
    "pizza","rocket","car","boat","fish","apple","banana","robot","crown","key",
    "balloon","guitar","umbrella","ladder","clock","cactus","ghost","dragon","castle","rainbow",
    "lion","bear","elephant","horse","cow","pig","duck","owl","penguin","rabbit",
    "frog","snake","turtle","bee","butterfly","spider","fox","panda","whale","dolphin",
    "shark","burger","donut","cupcake","cookie","cake","icecream","candy","egg","carrot",
    "pumpkin","cherry","lemon","orange","flower","leaf","mountain","fire","chair","table",
    "bed","lamp","door","book","pencil","hat","shoe","glove","phone","candle",
    "hammer","kite","bike","train","plane","wizard","pirate","clown","sword","heart",
    "gift","flag","ball","drum","bell"
  ],
  categories: {
    animals: ["cat","dog","lion","tiger","bear","monkey","elephant","giraffe","zebra","horse","cow","pig","sheep","goat","duck","chicken","owl","penguin","rabbit","mouse","frog","snake","turtle","bee","butterfly","spider","crab","octopus","whale","dolphin","shark","fox","wolf","deer","panda","koala","kangaroo","camel","bat","parrot"],
    food: ["pizza","apple","banana","burger","hotdog","donut","cupcake","cookie","cake","icecream","lollipop","candy","popcorn","sandwich","taco","pancake","egg","cheese","bread","carrot","corn","tomato","potato","pumpkin","strawberry","cherry","grape","lemon","orange","pear","peach","watermelon","pineapple","coconut","mushroom","broccoli"],
    nature: ["tree","sun","moon","star","cloud","rain","flower","leaf","grass","mountain","volcano","island","river","lake","wave","fire","lightning","tornado","snowflake","rock","shell","feather","acorn","forest","hill","cave","waterfall","rainbow"],
    objects: ["clock","key","chair","table","bed","lamp","door","window","mirror","book","pencil","pen","brush","scissors","ruler","backpack","hat","shoe","glove","phone","camera","laptop","bulb","candle","hammer","wrench","shovel","broom","bucket","umbrella","ladder","bottle","cup","spoon","fork","knife"],
    vehicles: ["car","truck","bus","train","plane","boat","ship","rocket","bike","scooter","motorcycle","tractor","helicopter","submarine","sailboat","canoe","van","taxi","ambulance","firetruck","anchor","wheel","kite","sled","skateboard"],
    fantasy: ["dragon","castle","wizard","fairy","mermaid","knight","pirate","ninja","clown","robot","alien","monster","witch","vampire","skeleton","zombie","genie","troll","giant","gnome","angel","superhero","sword","shield","wand","potion","crown","unicorn","treasure","gem"],
    music: ["guitar","drum","trumpet","piano","violin","flute","harp","bell","whistle","microphone","banjo"],
    shapes: ["heart","diamond","circle","square","triangle","arrow","star"],
    toys: ["ball","dice","puzzle","kite","yoyo","top","marble","teddy","blocks","balloon"],
    buildings: ["house","castle","tower","lighthouse","windmill","fountain","fence","gate","mailbox","bridge","tent","igloo","pyramid","statue"]
  },
  bluffNouns: [
    "banana","robot","wizard","potato","ninja","dragon","penguin","toaster","pirate","unicorn",
    "donut","hamster","volcano","kitten","monster","goblin","noodle","pickle","waffle","llama",
    "octopus","gnome","muffin","wombat","pancake","cactus","raccoon","panda","gremlin","meatball",
    "burrito","sloth","platypus","hedgehog","werewolf","jellyfish","narwhal","yeti","dinosaur","alien",
    "clown","knight","vampire","zombie","mermaid","fairy","genie","troll","witch","ghost",
    "walrus","beaver","otter","ferret","weasel","badger","moose","donkey","turkey","chicken",
    "lobster","shrimp","squid","crab","snail","beetle","cricket","hornet","spider","scorpion",
    "banjo","kazoo","trombone","bagpipe","xylophone","cowbell","tuba","harmonica","accordion","ukulele",
    "wizard","baron","captain","professor","chef","farmer","plumber","barber","juggler","mime",
    "cupcake","biscuit","pretzel","dumpling","taco","nacho","churro","bagel","pretzel","sundae",
    "gumball","jellybean","marshmallow","lollipop","cookie","brownie","donut","popsicle","pudding","custard",
    "spatula","whisk","ladle","mop","broom","plunger","kettle","blender","mixer","corkscrew",
    "goose","flamingo","peacock","toucan","pelican","seagull","pigeon","turkey","ostrich","dodo",
    "gargoyle","phoenix","griffin","kraken","cyclops","minotaur","centaur","pixie","sprite","imp"
  ],
  adjectives: [
    "flying","angry","giant","tiny","sneaky","royal","cosmic","grumpy","invisible","dancing",
    "exploding","sleepy","magical","turbo","evil","frozen","flaming","electric","golden","glowing",
    "spooky","fluffy","spicy","slimy","bouncy","wobbly","sparkly","mighty","fearless","clumsy",
    "greedy","curious","fancy","rusty","chubby","zippy","jolly","cranky","dizzy","gloomy",
    "howling","screaming","whispering","galloping","zooming","spinning","melting","bubbling","shrinking","towering",
    "ancient","legendary","cursed","enchanted","haunted","radioactive","robotic","feral","savage","noble",
    "wild","brave","silly","cheeky","dashing","rugged","sassy","funky"
  ]
};})();
