/* The arcade's catalogue. One row per game: folder, name, the line that sells
 * it, a short hook for tight spaces, and what it is. */
window.GAMES = [
  { id:'timeduel', n:'Time Duel', k:'Stop the clock dead on the target.',
    d:'Duel a friend, play blind, or run an eight-player tournament for the pot.',
    t:['Live','Skill'], p:'2–8', fresh:1 },
  { id:'f1', n:'Grand Prix 3D', k:'Race the world in three dimensions.',
    d:'Four circuits, a full grid, and Master Mode with bridges you have to jump.',
    t:['3D','Racing','Live'], p:'1–4' },
  { id:'obby', n:'Rainbow Obby', k:'Fifty stages. One wrong step.',
    d:'A 3D obstacle course across five worlds, with skins, trails and auras.',
    t:['3D','Platformer'], p:'1' },
  { id:'anime-tycoon', n:'Anime Tycoon', k:'Build the base. Unlock the power.',
    d:'A 3D tycoon where you earn your way to Gojo, Luffy and Naruto, then fight for it.',
    t:['3D','Tycoon'], p:'1' },
  { id:'scoop', n:'Basket Scoop', k:'Flick it off the floor. Watch it swish.',
    d:'Real arc, real rim, real net. Golden balls and a five-deep fire streak.',
    t:['Sports','Arcade'], p:'1' },
  { id:'cricket', n:'Super Over Cricket', k:'Six balls. One target. No second innings.',
    d:'Time the shot, chase the total, lift the cup — and set targets for the world.',
    t:['Sports','Challenge'], p:'1' },
  { id:'carrom', n:'Carrom Clash', k:'Pocket the queen, then cover her.',
    d:'Flick the striker against the computer or a friend, live, in a real room.',
    t:['Live','Board'], p:'2–4' },
  { id:'drawrush', n:'Draw Rush', k:'Draw it. Or bluff it.',
    d:'Secret Theme, Draw & Bluff, Disaster Drawing and an AI judge, plus a gallery.',
    t:['Live','Creative'], p:'2–8' },
  { id:'codewords', n:'Codewords', k:'One word. Two spies. No second guess.',
    d:'Two teams race to find their agents from single-word clues. Solo, party or online.',
    t:['Live','Word'], p:'2–8' },
  { id:'handcricket', n:'Hand Cricket League', k:'Same number, and you are out.',
    d:'An AI that learns your patterns, wild Crazy mode, and a World Cup to win.',
    t:['Live','Sports'], p:'1–2' },
  { id:'airhockey', n:'Air Hockey Arena', k:'First to seven. Nothing slows down.',
    d:'Physics-driven pucks, a career ladder, paddle skins and a global board.',
    t:['Sports','Arcade'], p:'1–2' },
  { id:'football', n:'Penalty Kings', k:'One kick decides the cup.',
    d:'A penalty shootout knockout in 2D or full 3D, match by match to the final.',
    t:['Sports','3D'], p:'1' },
  { id:'pptour', n:'Ping Pong Tour', k:'First-person table tennis.',
    d:'Climb from the qualifiers to the World Championship, unlocking rackets as you go.',
    t:['Sports','3D'], p:'1' },
  { id:'tennis', n:'Tennis Tour', k:'From the school court to the world final.',
    d:'Time the smash, read the return, and win your way up the tour.',
    t:['Sports'], p:'1–2' },
  { id:'karate', n:'Karate Champions', k:'Punch, kick, uppercut, repeat.',
    d:'Arcade fighting with real combos, all the way to the World Karate Cup.',
    t:['Fighting'], p:'1–2' },
  { id:'archer', n:'Archer Duel', k:'Aim, draw, arc, release.',
    d:'Gravity is real and so are the head shots. Each rival is tougher than the last.',
    t:['Skill','Duel'], p:'1' },
  { id:'fruit-arena', n:'Fruit Arena', k:'Slice everything. Except the bombs.',
    d:'Chain power-ups, spam the giant fruit, and unlock blades that change the feel.',
    t:['Arcade','Skill'], p:'1' },
  { id:'paper', n:'Paper Territory', k:'Leave the trail. Close the loop.',
    d:'Claim ground, dodge rivals, and own more of the board than anyone else.',
    t:['Arcade','Live'], p:'1' },
  { id:'stack', n:'Stack Tower', k:'One tap. One block. Do not drift.',
    d:'Perfect stacks build a combo and widen the tower back out. Global leaderboard.',
    t:['Arcade','Skill'], p:'1' },
  { id:'speedclicker', n:'Speed Clicker', k:'Fifteen seconds of pure tapping.',
    d:'One glowing orb, a draining ring, and a title waiting at the end of it.',
    t:['Arcade','Skill'], p:'1' },
  { id:'try', n:'One More Try', k:'The rules change while you run.',
    d:'A one-tap runner where gravity, spikes and gaps keep swapping on you.',
    t:['Arcade'], p:'1' },
  { id:'catch', n:'Basket Catch', k:'Catch it all before it lands.',
    d:'Move the basket, read the fall, and keep the streak alive.',
    t:['Arcade'], p:'1' },
  { id:'catch2', n:'Basket Catch 2', k:'Eat the fruit. Dodge the junk.',
    d:'Junk fills a one-way tummy meter — then Cheat Day arrives and everything changes.',
    t:['Arcade'], p:'1' },
  { id:'puzzles', n:'Puzzle Pad', k:'Eight brain games in one pad.',
    d:'Wordle, Connections, 2048, Sudoku, Simon and more, with streaks that carry over.',
    t:['Puzzle'], p:'1' },
  { id:'codebreaker', n:'Codebreaker', k:'Crack the code before the clock does.',
    d:'Search the room, piece the clues together, and get in. Secret-agent rules.',
    t:['Puzzle'], p:'1' },
  { id:'meme', n:'Meme Studio', k:'Build a scene. Watch it replay.',
    d:'Background, caption, effect and sound — then a gallery, likes and profiles.',
    t:['Creative','Live'], p:'1' },
  { id:'thisorthat', n:'This or That', k:'Messi or Ronaldo? Choose.',
    d:'Tap the one you like more, then see what everyone else actually picked.',
    t:['Party','Live'], p:'1' }
];
